version: 2.1

jobs:
  save-to-file:
    docker:
      - image: circleci/node:13.8.0
    working_directory:  /temp
    # steps
    steps:
      - run:
          name: "print Hello"
          command: |
            mkdir -p files
            echo 'Hello, World!' > files/hello.txt
      - persist_to_workspace:
          root: files
          paths:
            - /*

  read-from-file:
    docker:
      - image: circleci/node:13.8.0
    working_directory:  /temp
    # steps
    steps:
      - attach_workspace:
          at: /temp/files
      - run:
          name: "read file content"
          command:  |
            cat hello.txt

workflows:
  info-sharing-workflow:
    jobs:
      - save-to-file
      - read-from-file:
          requires: [save-to-file]
