version: 2.1

commands:
  print_pipeline_id:
    description: 'Like the name implies; print out pipeline ID.'
    steps:
      - run:
          name: 'Print Pipeline ID'
          command: |
            echo $CIRCLE_WORKFLOW_ID
jobs:
  show_pipeline_id:
    docker:
      - image:  circleci/node:13.8.0
    steps:
      - print_pipeline_id
  save-to-file:
    docker:
      - image: circleci/node:13.8.0
    working_directory:  /tmp
    # steps
    # https://circleci.com/docs/2.0/configuration-reference#persisttoworkspace
    steps:
      - run:
          name: "Save to file"
          command: |
            mkdir -p files/texts
            echo 'Hello, World!' > files/texts/hello.txt
      - persist_to_workspace:
          root: files
          paths:
            - texts/*

  read-from-file:
    docker:
      - image: circleci/node:13.8.0
    working_directory:  /tmp
    # steps
    steps:
      - attach_workspace:
          at: /tmp/files
      - run:
          name: "read file content"
          command:  |
            cat files/texts/hello.txt

workflows:
  info-sharing-workflow:
    jobs:
      - save-to-file
      - show_pipeline_id
      - read-from-file:
          requires: [save-to-file]
